백엔드 개발환경 설정
Doong-Ji/doong-ji.github.io pull request #26
Opened 2021-06-27 16:40 UTC by hyojin107

# 개발환경 설정

## 💡 해당 이슈
resolves #24

## 🛠 변경 사항
- 유저 권한명 변경 : guest, user, admin
- role테이블을 따로 나눴던 것을 account테이블에 합침

## 🙋‍♀ 리뷰어 참고 사항
- OAuth 적용을 마무리 못했습니다..😭 현재 OAuth 부분을 모두 걷어내고 pr을 올린 상태이며, 추후에 다시 작업 후 따로 pr을 올리도록 하겠습니다. 기능 개발 시에는 이상이 없으므로 바로 개발 착수 하시면 될 것 같습니다.
- 사용자 권한의 기본값은 GUEST이며, AlarmFlag(알람여부)의 기본값은 ON입니다.

## ✔ 리뷰어용 체크리스트
- [ ] 다음 기능에 대한 구현
    - [ ] Security + jwt 구현
    - [ ] 회원가입 기능 구현 (insert)
    - [ ] 로그인 기능 구현

- [ ] 다음 기능에 대한 유닛 테스트 통과
    - [ ]  jwt 테스트
    - [ ] 회원가입 기능 테스트
    - [ ] 로그인 기능 테스트

2021-06-29 14:20 UTC, kyung-Ho-sin submitted a review, later dismissed
수고하셨습니다!

2021-06-30 01:21 UTC, qlalzl9 reviewed
고생하셨습니다.
JWT 토큰 부분 어렵네요. 다음에 전체적인 흐름에 대해서 여쭤보겠습니다 ㅠ

2021-06-30 01:21 UTC, qlalzl9 commented on server/src/main/java/com/doongji/homepage/entity/account/Account.java
> +    @Column(nullable = false)
erd에는 NULL로 설정되어 있어서 NOT NULL로 바꾸겠습니다!

2021-06-30 01:21 UTC, qlalzl9 commented on server/src/main/java/com/doongji/homepage/service/AccountService.java
> +
Null 체크를 다른 파라미터도 해야 할 것 같습니다

2021-06-30 02:20 UTC, HwanChang commented on server/src/main/java/com/doongji/homepage/entity/account/Account.java
> +    @Enumerated(EnumType.STRING)
entity에서 enum을 사용할 때 DB 저장 시 enum 타입의 name으로 저장하기 위해 붙여주는 어노테이션입니다.

2021-06-30 02:23 UTC, HwanChang commented on server/src/main/java/com/doongji/homepage/entity/account/PartName.java
> +    NODEJS("노드js"),
백엔드는 분리하지말고 하나로 묶어주세요

2021-06-30 05:47 UTC, HwanChang requested changes
전체적으로 기존 코드를 그대로 사용한 부분이 많기 때문에 수정할 내용은 크게 없어보입니다.
하지만 기존 코드에 대한 이해가 없이 사용을 해버려서 추가된 부분에서는 몇 군데 놓친게 있는거 같아요.
확인해보시고 수정해주세요.
🙌🙌🙌

2021-06-30 12:49 UTC, hyojin107 commented on server/src/main/java/com/doongji/homepage/entity/account/Account.java
> +    @Column(nullable = false)
감사합니다🙌

2021-06-30 12:54 UTC, hyojin107 commented on server/src/main/java/com/doongji/homepage/service/AccountService.java
> +
다른 파라미터는 어딜 말하는건가요? 
생성자에 null 체크해주는걸 잊어서 추가해주었습니다!

2021-06-30 13:21 UTC, hyojin107 commented on server/src/test/java/com/doongji/homepage/service/account/AccountServiceTest.java
> +public class AccountServiceTest {
넵 수정해서 다시 올리도록하겠습니다

2021-06-30 13:31 UTC, hyojin107 commented on server/src/main/java/com/doongji/homepage/entity/account/PartName.java
> +public enum PartName {
해당 DTO부분의 반환타입을 enum으로 변경하였습니다.
네이밍도 Part로 수정하고 백엔드로 묶으면서, ETC값도 추가 해주었습니다.
감사합니다!

2021-06-30 13:34 UTC, kyung-Ho-sin commented on server/src/main/java/com/doongji/homepage/entity/account/Account.java
> +    @Enumerated(EnumType.STRING)
설명 감사합니다!

2021-06-30 13:43 UTC, hyojin107 commented on server/src/main/java/com/doongji/homepage/entity/account/Account.java
> +public class Account extends BaseTimeEntity {
쿼리문 확인결과 제대로 적용되어 있는걸 확인 했습니다! :)

2021-06-30 13:56 UTC, qlalzl9 commented on server/src/main/java/com/doongji/homepage/service/AccountService.java
> +
validation하는게 AccountService에서 하는 것과 Account 엔티티의 생성자에서 하는게 어떤 차이가 있나요?
 AccountService에는 패스워드와 파트만 하는 것 같은데 
 두 곳 모두 전체 값 체크를 하는게 맞을까요? 아니면 한 곳에서만 전체 값 체크를 하는게 맞는 걸까요?

2021-06-30 14:11 UTC, hyojin107 commented on server/src/main/java/com/doongji/homepage/service/AccountService.java
> +
만약 생성자에서 하지 않고 service에서 값 체크를 하게 된다면, 모든 service의 메서드마다 같은 validation코드를 반복적으로 해주어야해서 비효율적이 될 수 있습니다. 따라서 중복으로 validation하지 않도록 하기 위해, 기본적으로 생성자에서 체크를 해 주었습니다. 
여기서 패스워드만 service에서 값체크를 하는 이유는, 패스워드를 입력받는 경우가 회원가입(join)을 했을 때만 해당되기 때문입니다.

2021-07-01 00:34 UTC, qlalzl9 commented on server/src/main/java/com/doongji/homepage/service/AccountService.java
> +
감사합니다!

2021-07-01 00:36 UTC, qlalzl9 approved these changes

2021-07-01 14:58 UTC, kmlee95 approved these changes

2021-07-02 15:57 UTC, hyojin107 commented
토큰 생성 부분에서의 에러를 수정하였습니다!
추가로 http파일로 로그인 테스트를 추가하였으며(이를 위해 더미데이터 파일을 추가하였습니다). 이를 통해 로그인 요청 시 응답데이터가(jwt+account객체) 잘 나오는 것을 확인하실 수 있습니다.
테스트 실행시에는 로컬 서버를 먼저 실행 한 후 테스트하시기 바랍니다.

2021-07-05 01:42 UTC, HwanChang commented
Controller 부분도 테스트 코드를 통한 검증이 필요해요.
테스트를 위해 서버를 실행시키지 않고 단위 테스트가 진행될 수 있도록 해주세요.

2021-07-05 01:48 UTC, HwanChang requested changes
아직 수정이 필요한 부분이 있어 몇 가지 리뷰 남겨뒀습니다.
확인 부탁드려요.
🙌🙌🙌

2021-07-05 01:48 UTC, HwanChang commented on server/src/test/java/com/doongji/homepage/service/account/AccountServiceTest.java
>  @TestMethodOrder(MethodOrderer.OrderAnnotation.class)
Mockito를 사용하려면 Mockito를 활용한 테스트 코드 작성 방법을 좀 더 알아 볼 필요가 있을 것 같아요.

2021-07-05 01:48 UTC, HwanChang commented on server/src/main/java/com/doongji/homepage/controller/v1/account/dto/JoinRequest.java
> +    private String part;
네이밍만 변경할게 아니라 타입도 enum 타입으로 사용해줘야 할 것 같아요.

2021-07-05 01:48 UTC, HwanChang commented on server/src/main/java/com/doongji/homepage/service/AccountService.java
> +                        Part.valueOf(part.toUpperCase()), AlarmFlag.ON, Role.GUEST
처음 요청부터 enum 타입으로 받았다면 변경을 해줄 필요가 없을 것 같아요.
그리고 해당 enum의 값을 조작하는건 이렇게 밖에서 하기보단 enum 클래스 내부에서 하는게 더 좋지 않을까요?

2021-07-05 13:23 UTC, hyojin107 commented on server/src/test/java/com/doongji/homepage/service/account/AccountServiceTest.java
>  @TestMethodOrder(MethodOrderer.OrderAnnotation.class)
넵 보완하겠습니다

2021-07-05 13:24 UTC, hyojin107 commented on server/src/main/java/com/doongji/homepage/controller/v1/account/dto/JoinRequest.java
> +    private String part;
수정했습니다!

2021-07-05 13:25 UTC, hyojin107 commented on server/src/main/java/com/doongji/homepage/service/AccountService.java
> +                        Part.valueOf(part.toUpperCase()), AlarmFlag.ON, Role.GUEST
잘못생각했던 부분이 있었네요ㅎㅎ.. 요청 시 Enum으로 받을 수 있게끔 수정해주었습니다
리뷰 감사합니다🙌

2021-07-06 00:56 UTC, HwanChang requested changes
수정할 부분 몇군데 체크해뒀습니다.

확인 부탁드려요.
🙌🙌🙌

2021-07-06 00:56 UTC, HwanChang commented on server/src/main/java/com/doongji/homepage/controller/v1/account/dto/JoinRequest.java
> +    }
setter를 사용하면 enum을 적용시킬 수 있긴 하지만 enum의 값을 조작하는 부분이 밖에 나와있는게 좋은건 아닌거같아요.
그리고 굳이 이 하나 때문에 setter를 사용하기보단 좀 더 공통으로 사용할 수 있도록 관리를 해주면 좋을 것 같습니다.

2021-07-06 00:56 UTC, HwanChang commented on server/src/main/resources/schema.sql
> +);
JPA를 사용하여 entity를 직접 테이블로 생성해주고 있는데 이 쿼리는 어떤 내용때문에 추가가 된건가요?

2021-07-06 00:56 UTC, HwanChang commented on server/src/main/resources/i18n/messages.properties
> +error.notfound.details=Could not found ''{0}'' with query values ({1})
다국어 지원을 하려고 추가했다면 기본적으로 영어, 한국어는 지원해줘야 할 것 같아요.

2021-07-06 00:56 UTC, HwanChang commented on server/src/main/java/com/doongji/homepage/service/AccountService.java
> +                )
빌더패턴을 사용하면 파라미터를 좀 더 명확하게 보여줄 수 있을 것 같아요.

2021-07-06 00:56 UTC, HwanChang commented on server/src/main/java/com/doongji/homepage/security/JwtAuthentication.java
> +        checkNotNull(accountId, "userId must be provided.");
accountId, userId 문구가 다르네요.

2021-07-06 15:05 UTC, hyojin107 commented on server/src/main/resources/schema.sql
> +);
이부분은 http테스트를 위해서 추가했던건데, 단위 테스트는 서버를 실행하지 않고 해야한다고 피드백을 주셔서 삭제했습니다!

2021-07-06 15:18 UTC, hyojin107 commented on server/src/main/java/com/doongji/homepage/controller/v1/account/dto/JoinRequest.java
> +    }
듣고보니 모든 enum을 받을때마다 setter를 써준다는게 좋은 방식은 아닌것 같네요. 이 부분은 다시 고민해보고 수정해서 올리겠습니다🤔

2021-07-06 15:36 UTC, hyojin107 commented on server/src/main/resources/i18n/messages.properties
> +error.notfound.details=Could not found ''{0}'' with query values ({1})
한국어 추가해주었습니다. 감사합니다👍

2021-07-06 15:37 UTC, hyojin107 commented on server/src/main/java/com/doongji/homepage/security/JwtAuthentication.java
> +        checkNotNull(accountId, "userId must be provided.");
문구 수정하였습니다.

2021-07-06 15:52 UTC, hyojin107 commented on server/src/main/java/com/doongji/homepage/service/AccountService.java
> +                )
생성자에서 validation체크를 해준 상황에서, 빌더 패턴을 사용하게 될 때 두 가지 질문사항이 있습니다.
1. 빌더패턴을 적용하면, 현재 사용하고 있는 점층적 생성자 패턴은 사용하지 않는건가요?
2. 롬복이 아닌 Builder클래스를 직접 구현하여, 여기서 본 클래스에 값을 세팅하기 전에 validation을 체크 해주어야하는건지 궁금합니다.

2021-08-05 10:39 UTC, hyojin107 commented on server/src/main/java/com/doongji/homepage/controller/v1/account/dto/JoinRequest.java
> +    }
setter 대신 Enum에서 관리할 수 있도록 수정하였습니다. 감사합니다. 🙂

2021-08-08 12:26 UTC, hyojin107 commented on server/src/test/java/com/doongji/homepage/service/account/AccountServiceTest.java
> +public class AccountServiceTest {
수정완료했습니다. 감사합니다! 😀😁

2021-09-25 10:05 UTC, HwanChang approved these changes

2021-09-25 10:07 UTC, merged